type Comment {
    userName: String!
    message: String!
    post: Post
}

type Post {
    userName: String!
    description: String
    image: String!
    imageDelete: String!
    tags: [String!]
    likes: [String!]
    comments: [Comment] @relation
}

type User {
    userName: String! @unique
    password: String!
}

type Query {
  allPosts: [Post!]! 
  allComments: [Comment!]
  allUsers: [User!]
  getUserByName(userName: String): User
  getPostByName(userName: String): [Post!]!
  getByTag(tags: String): [Post]

}

